### register
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "wildan2",
    "password": "wildan12",
    "roleAccess": [
        { "users":["GET", "POST","PUT", "DELETE"] }
    ]
}

### login
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "wildan",
    "password": "wildan12"
}

### delete
DELETE http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: token ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5U1dRaU9pSmtPVEUyWVdaalppMDNNRE5rTFRRNE9HTXRPREEzWWkxallUUmhNVGN3WW1aa09XTWlMQ0p5YjJ4bFFXTmpaWE56SWpwYmV5SjFjMlZ5Y3lJNld5SkhSVlFpTENKUVQxTlVJaXdpVUZWVUlpd2lSRVZNUlZSRklsMTlYU3dpYVdGMElqb3hOakV5T0RZMU9EazNMQ0psZUhBaU9qRTJORFEwTURFNE9UZDkuYUtIcExyc1l1aHJvVUxScDI2dVA5d1ZFU3BhZzdTeDA3MHJEV3E5SEs4aFZlTzFYOFd1djhNOEhHVUtVREtzTlBsZDljSkdYdmpzeTFMN29iSXNGaXpRS29VQnFOVVdBV0JuNDczUVRMbG5UNTRQamdhbFhfaGRLeTYwTTFfVFl2YTVONUJoeWUwMlVHdi1wT3NuaXI0ejhlSDlpcnJZS09RNGoxNVd1RkxSVk8yUUtoZnpMQlFBTGE5a1RhVmVaNTMtdVNZUzRaUk03RWdYcDlkTWJ5a1FWNmRsVWxULW1iVkU0Qi04SlZBTlphR081X0hrSl9mMW8teDR3ZWhEN2RScEl6ZUFZOFMyTzJRMXl2Sm9DMWtvejEzdndyUTR3T29Sa1JOWk5vS08ydk1SQk9SNHdyd1llXzFkUXNKZ2tKVHVoMUpBUXl2MmpCWkJtY2tyaU53

{
    "userId": "d916afcf-703d-488c-807b-ca4a170bfd9c"
}

### update
PUT http://localhost:3000/users/ab017e92-71fc-4ed0-8ecc-d5122a788144 HTTP/1.1
Content-Type: application/json
Authorization: token ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5U1dRaU9pSmtPVEUyWVdaalppMDNNRE5rTFRRNE9HTXRPREEzWWkxallUUmhNVGN3WW1aa09XTWlMQ0p5YjJ4bFFXTmpaWE56SWpwYmV5SjFjMlZ5Y3lJNld5SkhSVlFpTENKUVQxTlVJaXdpVUZWVUlpd2lSRVZNUlZSRklsMTlYU3dpYVdGMElqb3hOakV5T0RZMU9EazNMQ0psZUhBaU9qRTJORFEwTURFNE9UZDkuYUtIcExyc1l1aHJvVUxScDI2dVA5d1ZFU3BhZzdTeDA3MHJEV3E5SEs4aFZlTzFYOFd1djhNOEhHVUtVREtzTlBsZDljSkdYdmpzeTFMN29iSXNGaXpRS29VQnFOVVdBV0JuNDczUVRMbG5UNTRQamdhbFhfaGRLeTYwTTFfVFl2YTVONUJoeWUwMlVHdi1wT3NuaXI0ejhlSDlpcnJZS09RNGoxNVd1RkxSVk8yUUtoZnpMQlFBTGE5a1RhVmVaNTMtdVNZUzRaUk03RWdYcDlkTWJ5a1FWNmRsVWxULW1iVkU0Qi04SlZBTlphR081X0hrSl9mMW8teDR3ZWhEN2RScEl6ZUFZOFMyTzJRMXl2Sm9DMWtvejEzdndyUTR3T29Sa1JOWk5vS08ydk1SQk9SNHdyd1llXzFkUXNKZ2tKVHVoMUpBUXl2MmpCWkJtY2tyaU53
Signature: ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SjFjMlZ5Ym1GdFpTSTZJbmRwYkdSaGJqSjFjR1JoZEdVaUxDSnliMnhsUVdOalpYTnpJanBiZXlKMWMyVnljeUk2V3lKSFJWUWlMQ0pRVDFOVUlpd2lVRlZVSWwxOVhYMC4zc3dIU2hhcjlJRzhhUHk0aF96NTN0SFd3cEZXLVB1ZTZ2SHV0SDdTaEcyTFdLRGhuWEU0cWI2cUJMcUFrZlNIcTA2V3F1WjhHSGw3SjdITmM0MFZjQnJJbExTWWc2ZlIza0RLTmRfN2p6c29UeHMzM1lzRHBhN1M5VGxQc2xOLVJ0NkFMaTM4dXgwVTV5aV81ME1OMnZmTWVhN2lGYlFNS3FGYlZiNFpiSnpEQ1Q3ZjNHZmNKU09MOHpfbjBxQlppeEJ5elpEMk9wTllUUnQ0Um9BUjhfdVNZdDEtV3BoU2J5aWhnOE5GY09xdXhuM2NNbVRDcm1iZHdBNEtac09paFV1VVdiSkozZmlsNnZObjgxT1A0Wm5ZQTI4dkVNMTM1MVB4dm9MNXJfVWFfLUtmMjUwNHg2Q29ZSWpDdVY1TnJCd3ZTMXpMZzVYcmdGM1BLM25XSWc=

{
    "username": "wildan2update",
    "roleAccess": [
        { "users":["GET", "POST","PUT","DELETE"] }
    ]
}

### verify
POST http://localhost:3000/auth/verify HTTP/1.1
Content-Type: application/json

{
    "token": "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5U1dRaU9pSmtPVEUyWVdaalppMDNNRE5rTFRRNE9HTXRPREEzWWkxallUUmhNVGN3WW1aa09XTWlMQ0p5YjJ4bFFXTmpaWE56SWpwYmV5SjFjMlZ5Y3lJNld5SkhSVlFpTENKUVQxTlVJaXdpVUZWVUlpd2lSRVZNUlZSRklsMTlYU3dpYVdGMElqb3hOakV5T0RZMU9EazNMQ0psZUhBaU9qRTJORFEwTURFNE9UZDkuYUtIcExyc1l1aHJvVUxScDI2dVA5d1ZFU3BhZzdTeDA3MHJEV3E5SEs4aFZlTzFYOFd1djhNOEhHVUtVREtzTlBsZDljSkdYdmpzeTFMN29iSXNGaXpRS29VQnFOVVdBV0JuNDczUVRMbG5UNTRQamdhbFhfaGRLeTYwTTFfVFl2YTVONUJoeWUwMlVHdi1wT3NuaXI0ejhlSDlpcnJZS09RNGoxNVd1RkxSVk8yUUtoZnpMQlFBTGE5a1RhVmVaNTMtdVNZUzRaUk03RWdYcDlkTWJ5a1FWNmRsVWxULW1iVkU0Qi04SlZBTlphR081X0hrSl9mMW8teDR3ZWhEN2RScEl6ZUFZOFMyTzJRMXl2Sm9DMWtvejEzdndyUTR3T29Sa1JOWk5vS08ydk1SQk9SNHdyd1llXzFkUXNKZ2tKVHVoMUpBUXl2MmpCWkJtY2tyaU53",
    "service": "users",
    "method": "DELETE"
}

### signature
POST http://localhost:3000/auth/validate/signature HTTP/1.1
Content-Type: application/json

{
    "signature":"ZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUo5LmV5SjFjMlZ5Ym1GdFpTSTZJbmRwYkdSaGJqSjFjR1JoZEdVaUxDSnliMnhsUVdOalpYTnpJanBiZXlKMWMyVnljeUk2V3lKSFJWUWlMQ0pRVDFOVUlpd2lVRlZVSWwxOVhYMC4zc3dIU2hhcjlJRzhhUHk0aF96NTN0SFd3cEZXLVB1ZTZ2SHV0SDdTaEcyTFdLRGhuWEU0cWI2cUJMcUFrZlNIcTA2V3F1WjhHSGw3SjdITmM0MFZjQnJJbExTWWc2ZlIza0RLTmRfN2p6c29UeHMzM1lzRHBhN1M5VGxQc2xOLVJ0NkFMaTM4dXgwVTV5aV81ME1OMnZmTWVhN2lGYlFNS3FGYlZiNFpiSnpEQ1Q3ZjNHZmNKU09MOHpfbjBxQlppeEJ5elpEMk9wTllUUnQ0Um9BUjhfdVNZdDEtV3BoU2J5aWhnOE5GY09xdXhuM2NNbVRDcm1iZHdBNEtac09paFV1VVdiSkozZmlsNnZObjgxT1A0Wm5ZQTI4dkVNMTM1MVB4dm9MNXJfVWFfLUtmMjUwNHg2Q29ZSWpDdVY1TnJCd3ZTMXpMZzVYcmdGM1BLM25XSWc=",
    "content": {
        "username": "wildan2update",
        "roleAccess": [
            { "users":["GET", "POST","PUT"] }
        ]
    }
}