### register
POST http://localhost:7020/register
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"password"
}

### login
POST http://localhost:7020/login
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"password"
}

### list
GET http://localhost:7020/list