### login
POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "wildan12",
    "password": "wildan12"
}

### register
POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "wildan",
    "password": "wildan12",
    "status": "sales"
}

### generate token
POST http://localhost:3001/auth/generate HTTP/1.1
Content-Type: application/json

{
    "userId": "ca238cb4-ba89-44cc-b561-a0063ba193e3"
}

### verify token
POST http://localhost:3001/auth/verify HTTP/1.1
Content-Type: application/json

{
    "token": "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5U1dRaU9pSmpZVEl6T0dOaU5DMWlZVGc1TFRRMFkyTXRZalUyTVMxaE1EQTJNMkpoTVRrelpUTWlMQ0pwWVhRaU9qRTJNVEk0TWpVd09EVXNJbVY0Y0NJNk1UWTBORE0yTVRBNE5YMC5MYXlRR2dwc2JhbDJTcmlwU1V5TTE4ZllrcmM0d0p5Rjc5ZDctYk9LTFQ0"
}