### login
POST http://localhost:3001/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "wildananugrah@gmail.com",
    "password": "password!"
}

### register
POST http://localhost:3001/api/v1/users/register HTTP/1.1
Content-Type: application/json

{
    "email": "wildananugrah@gmail.com",
    "password": "password!"
}

### add room
POST http://localhost:3001/api/v1/rooms HTTP/1.1
Content-Type: application/json

{
    "roomName": "wildanroom"
}

### get rooms
GET http://localhost:3001/api/v1/rooms HTTP/1.1
Content-Type: application/json

### delete room
DELETE http://localhost:3001/api/v1/rooms HTTP/1.1
Content-Type: application/json

{ "roomId": "eb4364bf-f58d-4629-b89a-3b1fa5a59a6d" }

###
POST http://localhost:3001/api/v1/chats HTTP/1.1
Content-Type: application/json

{
    "roomID":"cc0a63ab-f781-4c2f-92af-c14e0a2aeb16",
    "sentBy":"user@gmail.com",
    "message":"ilnda"
}

